import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ChromePicker } from 'react-color'
import { useState } from 'react'

export default function Home() {
  const [color,setColor] =useState("")
  const [showColorPicker, setShowColorPicker] = useState(false)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button
         onClick={()=>setShowColorPicker(showColorPicker =>!showColorPicker)}
         >
          {showColorPicker ? 'Close color Picker':'Pick a color'}
        </button>
        {
          showColorPicker &&    (
           <ChromePicker
            color={color} 
            onChange={updatedColor =>setColor(updatedColor.hex)}
             />
          )
        }
    <h2>
      you picked {color}
      </h2>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
